### ISSUE TITLE
cannot ghfetch my dotfiles

### ISSUE THREAD

**Issue by olivertzeng** [ghfetch/ghfetch#3]
```
❯ ghfetch olivertzeng/dotfiles
Traceback (most recent call last):
  File "/bin/ghfetch", line 287, in <module>
    main()
  File "/bin/ghfetch", line 284, in main
    print_output(fetched_info)
  File "/bin/ghfetch", line 251, in print_output
    output[n + 14] += ', '.join([(f"{title(k, get_lang_color(languages, k))}: {text(v)}") for k, v in fetched_info["languages"].items()][2:])
    ~~~~~~^^^^^^^^
IndexError: list index out of range
```

**Comment by nullgaro** [comment]
Solved in the new release 1.5.4
